version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-local
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./my-sql/.env
    volumes:
      - mysql.data:/var/lib/mysql
      - ./my-sql/users/users.csv:/usr/share/mysql/sql/users.csv
      - ./my-sql/mysql-config.cnf:/etc/mysql/conf.d/mysql.cnf:ro

volumes:
  mysql.data:
    name: mysql.data